# -*- coding: utf-8 -*-
"""Project 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16hohTgsj8wZK0A3Odelspg8f8YMz2O7S
"""

#import libraries

import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler
tfidf = TfidfVectorizer()

import matplotlib.pyplot as plt

#import dataset

df = pd.read_csv("/content/online courses  across platforms.csv")
df

df =df.head(700)
print(df.head())

#data preprocessing

df = df.fillna('')
df
df = df.drop_duplicates()
df

#4. Feature Engineering

df['features'] = df['course'] + " " + df['skills']
df

df['features']

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')
df['rating'] = df['rating'].fillna(0)
scaler = MinMaxScaler()
df['Rating_Normalized'] = scaler.fit_transform(df[['rating']])
df

# ML model training

courses = [
    "Google Cybersecurity"
    "Google Data Analytics"
    "Google IT Support"
]

tfidf = TfidfVectorizer()

result = tfidf.fit_transform(courses)

print(result.toarray())

print(tfidf.get_feature_names_out())

tfidf = TfidfVectorizer(stop_words='english')
feature_matrix = tfidf.fit_transform(df['features'])

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(feature_matrix)

tfidf.fit_transform(df['course'])

#Recommendation courses

def recommend(course_name):

    # Corrected: Using 'course' (singular) as the column name in df
    index = df[df['course'] == course_name].index[0]

    scores = list(enumerate(similarity[index]))

    scores = sorted(scores,
                    key=lambda x: x[1],
                    reverse=True)

    print("Recommended Courses:")

    for i in scores[1:4]:
        print(df.iloc[i[0]]['course'])

recommend("Google IT Support")

actual_courses = [
    "The Bits and Bytes of Computer Networking",
    "Google IT Support",
    "Computer Networking Basics"
]

recommended_courses = [
    "The Bits and Bytes of Computer Networking",
    "Suporte em TI do Google",
    "Soporte de Tecnologías de la Información de Google"
]

#Confusion Metrics

metrics = ['Precision', 'Recall', 'F1-Score']
scores = [0.33, 0.33, 0.33]

plt.bar(metrics, scores)

plt.title("Recommendation System Metrics")
plt.xlabel("Metrics")
plt.ylabel("Score")

plt.show()

# Precision curve diagram

test = [1, 2, 3, 4, 5]
precision = [0.60, 0.70, 0.75, 0.82, 0.90]

plt.plot(test, precision, marker='o')

plt.title("Precision Curve")
plt.xlabel("Test Number")
plt.ylabel("Precision")
plt.grid(True)

plt.show()